### ISSUE TITLE
依存パッケージを pip で管理できるようにしてほしい

### ISSUE THREAD

**Issue by co3k** [co33k/co33k#1]
ぱっと見だと以下の標準外のパッケージが必要っぽい（他にもあるかもしれない）
- MeCab
- tweepy

ということで、現状動作している環境において `pip freeze` の出力を `requirements.txt` とかに書きだして、 `pip install -r requirements.txt` とかでインストールできるようになっていてほしいです。

**Comment by naoyat** [comment]
了解やで

**Comment by co3k** [comment]
Thanks!
